baseURL = "https://wiki.fibra.click"
languageCode = "it-it"
title = "FibraClick Wiki"

theme = "hugo-journal"

disableKinds = ["RSS", "taxonomyTerm"]
preserveTaxonomyNames = true

[params]
  description = "Dubbi sugli operatori telefonici, fibra ottica, copertura? Su FibraClick Wiki troverai molte risposte"
  logo = "/images/logo.png"

[permalinks]
  posts = "/:slug"
  categories = "/:slug"

[taxonomies]
  category = "categories"
