baseURL = "https://wiki.fibra.click"
languageCode = "it-IT"
title = "FibraClick Wiki"

theme = "hugo-journal"

disableKinds = ["RSS", "taxonomyTerm", "section"]
preserveTaxonomyNames = true
footnoteReturnLinkContents = "⤴"
removePathAccents = true

[params]
  description = "Dubbi sugli operatori telefonici, fibra ottica, copertura? Su FibraClick Wiki troverai molte risposte"
  logo = "/images/logo.png"
  analytics = "UA-65084561-3"

[permalinks]
  posts = "/:slug"
  categories = "/c/:slug"

[taxonomies]
  category = "categories"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
